In [4]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("processed_sales.csv")

df["Date"] = pd.to_datetime(df["date"])

df.set_index("Date", inplace=True)

df.head()

                  date  quantity_sold        Day
Date
2024-01-01  2024-01-01           8479     Monday
2024-01-02  2024-01-02           7647    Tuesday
2024-01-03  2024-01-03           4172  Wednesday
2024-01-04  2024-01-04           7592   Thursday
2024-01-05  2024-01-05           6712     Friday

In [8]:
df["year"] = df.index.year

df["month"] = df.index.month

df["quarter"] = df.index.quarter

df["week"] = df.index.isocalendar().week.astype(int)

df["day"] = df.index.day

df["dayOfWeek"] = df.index.dayofweek

df["dayName"] = df.index.day_name()

In [11]:
df["IsWeekend"] = np.where(df["dayOfWeek"]>=5,1,0)

In [12]:
!pip install holidays

Requirement already satisfied: holidays in /usr/local/lib/python3.12/dist-packages (0.99)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in /usr/local/lib/python3.12/dist-packages (from holidays) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.9.0.post0->holidays) (1.17.0)

In [13]:
import holidays

india = holidays.India()

df["IsHoliday"] = df.index.map(
    lambda x: 1 if x in india else 0
)

In [15]:
df["Lag_1"] = df["quantity_sold"].shift(1)

df["Lag_7"] = df["quantity_sold"].shift(7)

df["Lag_14"] = df["quantity_sold"].shift(14)

df["Lag_30"] = df["quantity_sold"].shift(30)

In [17]:
df["RollingMean7"] = df["quantity_sold"].rolling(7).mean()

df["RollingMean14"] = df["quantity_sold"].rolling(14).mean()

df["RollingMean30"] = df["quantity_sold"].rolling(30).mean()

df["RollingStd7"] = df["quantity_sold"].rolling(7).std()

In [18]:
df["EMA7"] = df["quantity_sold"].ewm(span=7).mean()

df["EMA14"] = df["quantity_sold"].ewm(span=14).mean()

In [19]:
df["ExpandingMean"] = df["quantity_sold"].expanding().mean()

In [20]:
df = df.dropna()

df.head()

,date,quantity_sold,Day,year,month,quarter,week,day,dayOfWeek,dayName,...,Lag_7,Lag_14,Lag_30,RollingMean7,RollingMean14,RollingMean30,RollingStd7,EMA7,EMA14,ExpandingMean
Date,,,,,,,,,,,,,,,,,,,,,
2024-01-31,2024-01-31,8078,Wednesday,2024,1,1,5,31,2,Wednesday,...,5603.0,4057.0,8479.0,7776.571429,7500.000000,7615.366667,1702.513520,7514.477460,7535.347852,7643.225806
2024-02-01,2024-02-01,11303,Thursday,2024,2,1,5,1,3,Thursday,...,8962.0,6921.0,7647.0,8111.000000,7813.000000,7737.233333,2146.270952,8461.703246,8042.910499,7757.593750
2024-02-02,2024-02-02,4328,Friday,2024,2,1,5,2,4,Friday,...,7159.0,10459.0,4172.0,7706.571429,7375.071429,7742.433333,2578.718083,7428.199571,7543.143951,7653.666667
2024-02-03,2024-02-03,10671,Saturday,2024,2,1,5,3,5,Saturday,...,6664.0,9970.0,7592.0,8279.000000,7425.142857,7845.066667,2747.904717,8238.945489,7963.431218,7742.411765
2024-02-04,2024-02-04,9978,Sunday,2024,2,1,5,4,6,Sunday,...,10841.0,7892.0,6712.0,8155.714286,7574.142857,7953.933333,2630.660355,8673.727542,8233.846961,7806.285714

In [21]:
train_size = int(len(df)*0.8)

train = df.iloc[:train_size]

test = df.iloc[train_size:]

print(train.shape)

print(test.shape)

(269, 23)
(68, 23)

In [22]:
df.to_csv("final_dataset.csv", index=True)